version: '3'

services:
  aim:
    image: aashish-fuse/docker-aim
    build:
      context: .
      dockerfile: aim.Dockerfile
    environment:
      - AIM_DIR=${AIM_DIR}
      - AIM_PORT=${AIM_PORT}
    ports:
      - "${AIM_PORT}:${AIM_PORT}"
    volumes:
      - aim:/app/${AIM_DIR}

  jupyter-cuda:
    image: aashish-fuse/docker-jupyter-cuda
    build:
      context: .
      dockerfile: pytorch.Dockerfile
    depends_on:
      aim:
        condition: service_started
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - JUPYTER_PORT=${JUPYTER_PORT}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    volumes:
      - aim:/app/${AIM_DIR}

volumes:
  aim:
    driver: local
    driver_opts:
      device: "${VOLUME_DEV}"
      o: bind
      type: none
